/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RideId = IDL.Nat;
export const RideStatus = IDL.Variant({
  'Accepted' : IDL.Null,
  'Requested' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const GenderPreference = IDL.Variant({
  'Male' : IDL.Null,
  'NoPreference' : IDL.Null,
  'Female' : IDL.Null,
});
export const LandmarkId = IDL.Nat;
export const RideType = IDL.Variant({
  'WomenOnly' : IDL.Null,
  'General' : IDL.Null,
});
export const RidePublic = IDL.Record({
  'id' : RideId,
  'status' : RideStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'driverId' : IDL.Opt(UserId),
  'startedAt' : IDL.Opt(Timestamp),
  'totalPassengers' : IDL.Nat,
  'genderPreference' : GenderPreference,
  'passengerId' : UserId,
  'pickupLandmarkId' : LandmarkId,
  'farePerPassenger' : IDL.Float64,
  'rideType' : RideType,
  'requestedAt' : Timestamp,
  'dropoffLandmarkId' : LandmarkId,
});
export const CreateRideRequest = IDL.Record({
  'totalPassengers' : IDL.Nat,
  'genderPreference' : GenderPreference,
  'pickupLandmarkId' : LandmarkId,
  'rideType' : RideType,
  'dropoffLandmarkId' : LandmarkId,
});
export const LandmarkType = IDL.Variant({
  'Station' : IDL.Null,
  'Landmark' : IDL.Null,
  'Metro' : IDL.Null,
  'Chowk' : IDL.Null,
  'Hospital' : IDL.Null,
});
export const Landmark = IDL.Record({
  'id' : LandmarkId,
  'latitude' : IDL.Float64,
  'landmarkType' : LandmarkType,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const DriverProfilePublic = IDL.Record({
  'userId' : UserId,
  'vehicleNumber' : IDL.Text,
  'licenseId' : IDL.Text,
  'isVerified' : IDL.Bool,
  'totalRides' : IDL.Nat,
  'avgRating' : IDL.Float64,
});
export const Role = IDL.Variant({
  'Driver' : IDL.Null,
  'Passenger' : IDL.Null,
});
export const Gender = IDL.Variant({
  'Male' : IDL.Null,
  'Female' : IDL.Null,
  'Other' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'photoUrl' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const PassengerProfilePublic = IDL.Record({
  'userId' : UserId,
  'totalRides' : IDL.Nat,
  'avgRating' : IDL.Float64,
});
export const RatingId = IDL.Nat;
export const Rating = IDL.Record({
  'id' : RatingId,
  'createdAt' : Timestamp,
  'rideId' : RideId,
  'toUserId' : UserId,
  'score' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
  'fromUserId' : UserId,
});
export const UserRatingSummary = IDL.Record({
  'totalRatings' : IDL.Nat,
  'avgScore' : IDL.Float64,
  'userId' : UserId,
  'ratings' : IDL.Vec(Rating),
});
export const AvailableDriver = IDL.Record({
  'driverId' : UserId,
  'vehicleNumber' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isVerified' : IDL.Bool,
  'totalRides' : IDL.Nat,
  'avgRating' : IDL.Float64,
});
export const FarePreview = IDL.Record({
  'totalFare' : IDL.Float64,
  'fareFor1' : IDL.Float64,
  'fareFor2' : IDL.Float64,
  'fareFor3' : IDL.Float64,
  'fareFor4' : IDL.Float64,
  'distanceKm' : IDL.Float64,
});
export const RegisterDriverRequest = IDL.Record({
  'vehicleNumber' : IDL.Text,
  'licenseId' : IDL.Text,
});
export const RegisterUserRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'photoUrl' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const SubmitRatingRequest = IDL.Record({
  'rideId' : RideId,
  'toUserId' : UserId,
  'score' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'acceptRide' : IDL.Func([RideId], [RidePublic], []),
  'cancelRide' : IDL.Func([RideId], [RidePublic], []),
  'createRide' : IDL.Func([CreateRideRequest], [RidePublic], []),
  'getAllLandmarks' : IDL.Func([], [IDL.Vec(Landmark)], ['query']),
  'getDriverProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(DriverProfilePublic)],
      ['query'],
    ),
  'getDriverRideHistory' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getIncomingRideRequests' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getLandmarkById' : IDL.Func([LandmarkId], [IDL.Opt(Landmark)], ['query']),
  'getLandmarkDistance' : IDL.Func(
      [LandmarkId, LandmarkId],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getLandmarksByCity' : IDL.Func([IDL.Text], [IDL.Vec(Landmark)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getMyRideHistory' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
  'getPassengerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(PassengerProfilePublic)],
      ['query'],
    ),
  'getRatingsForUser' : IDL.Func([UserId], [UserRatingSummary], ['query']),
  'getRideById' : IDL.Func([RideId], [IDL.Opt(RidePublic)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'listAvailableDrivers' : IDL.Func(
      [RideId],
      [IDL.Vec(AvailableDriver)],
      ['query'],
    ),
  'markDropoff' : IDL.Func([RideId], [RidePublic], []),
  'markPickup' : IDL.Func([RideId], [RidePublic], []),
  'previewFare' : IDL.Func([LandmarkId, LandmarkId], [FarePreview], ['query']),
  'registerDriverProfile' : IDL.Func(
      [RegisterDriverRequest],
      [DriverProfilePublic],
      [],
    ),
  'registerUser' : IDL.Func([RegisterUserRequest], [UserPublic], []),
  'rejectRide' : IDL.Func([RideId], [RidePublic], []),
  'submitRating' : IDL.Func([SubmitRatingRequest], [Rating], []),
  'updateUserPhoto' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RideId = IDL.Nat;
  const RideStatus = IDL.Variant({
    'Accepted' : IDL.Null,
    'Requested' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const GenderPreference = IDL.Variant({
    'Male' : IDL.Null,
    'NoPreference' : IDL.Null,
    'Female' : IDL.Null,
  });
  const LandmarkId = IDL.Nat;
  const RideType = IDL.Variant({
    'WomenOnly' : IDL.Null,
    'General' : IDL.Null,
  });
  const RidePublic = IDL.Record({
    'id' : RideId,
    'status' : RideStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'driverId' : IDL.Opt(UserId),
    'startedAt' : IDL.Opt(Timestamp),
    'totalPassengers' : IDL.Nat,
    'genderPreference' : GenderPreference,
    'passengerId' : UserId,
    'pickupLandmarkId' : LandmarkId,
    'farePerPassenger' : IDL.Float64,
    'rideType' : RideType,
    'requestedAt' : Timestamp,
    'dropoffLandmarkId' : LandmarkId,
  });
  const CreateRideRequest = IDL.Record({
    'totalPassengers' : IDL.Nat,
    'genderPreference' : GenderPreference,
    'pickupLandmarkId' : LandmarkId,
    'rideType' : RideType,
    'dropoffLandmarkId' : LandmarkId,
  });
  const LandmarkType = IDL.Variant({
    'Station' : IDL.Null,
    'Landmark' : IDL.Null,
    'Metro' : IDL.Null,
    'Chowk' : IDL.Null,
    'Hospital' : IDL.Null,
  });
  const Landmark = IDL.Record({
    'id' : LandmarkId,
    'latitude' : IDL.Float64,
    'landmarkType' : LandmarkType,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const DriverProfilePublic = IDL.Record({
    'userId' : UserId,
    'vehicleNumber' : IDL.Text,
    'licenseId' : IDL.Text,
    'isVerified' : IDL.Bool,
    'totalRides' : IDL.Nat,
    'avgRating' : IDL.Float64,
  });
  const Role = IDL.Variant({ 'Driver' : IDL.Null, 'Passenger' : IDL.Null });
  const Gender = IDL.Variant({
    'Male' : IDL.Null,
    'Female' : IDL.Null,
    'Other' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'photoUrl' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const PassengerProfilePublic = IDL.Record({
    'userId' : UserId,
    'totalRides' : IDL.Nat,
    'avgRating' : IDL.Float64,
  });
  const RatingId = IDL.Nat;
  const Rating = IDL.Record({
    'id' : RatingId,
    'createdAt' : Timestamp,
    'rideId' : RideId,
    'toUserId' : UserId,
    'score' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
    'fromUserId' : UserId,
  });
  const UserRatingSummary = IDL.Record({
    'totalRatings' : IDL.Nat,
    'avgScore' : IDL.Float64,
    'userId' : UserId,
    'ratings' : IDL.Vec(Rating),
  });
  const AvailableDriver = IDL.Record({
    'driverId' : UserId,
    'vehicleNumber' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isVerified' : IDL.Bool,
    'totalRides' : IDL.Nat,
    'avgRating' : IDL.Float64,
  });
  const FarePreview = IDL.Record({
    'totalFare' : IDL.Float64,
    'fareFor1' : IDL.Float64,
    'fareFor2' : IDL.Float64,
    'fareFor3' : IDL.Float64,
    'fareFor4' : IDL.Float64,
    'distanceKm' : IDL.Float64,
  });
  const RegisterDriverRequest = IDL.Record({
    'vehicleNumber' : IDL.Text,
    'licenseId' : IDL.Text,
  });
  const RegisterUserRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'photoUrl' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const SubmitRatingRequest = IDL.Record({
    'rideId' : RideId,
    'toUserId' : UserId,
    'score' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'acceptRide' : IDL.Func([RideId], [RidePublic], []),
    'cancelRide' : IDL.Func([RideId], [RidePublic], []),
    'createRide' : IDL.Func([CreateRideRequest], [RidePublic], []),
    'getAllLandmarks' : IDL.Func([], [IDL.Vec(Landmark)], ['query']),
    'getDriverProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(DriverProfilePublic)],
        ['query'],
      ),
    'getDriverRideHistory' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getIncomingRideRequests' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getLandmarkById' : IDL.Func([LandmarkId], [IDL.Opt(Landmark)], ['query']),
    'getLandmarkDistance' : IDL.Func(
        [LandmarkId, LandmarkId],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getLandmarksByCity' : IDL.Func([IDL.Text], [IDL.Vec(Landmark)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getMyRideHistory' : IDL.Func([], [IDL.Vec(RidePublic)], ['query']),
    'getPassengerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(PassengerProfilePublic)],
        ['query'],
      ),
    'getRatingsForUser' : IDL.Func([UserId], [UserRatingSummary], ['query']),
    'getRideById' : IDL.Func([RideId], [IDL.Opt(RidePublic)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'listAvailableDrivers' : IDL.Func(
        [RideId],
        [IDL.Vec(AvailableDriver)],
        ['query'],
      ),
    'markDropoff' : IDL.Func([RideId], [RidePublic], []),
    'markPickup' : IDL.Func([RideId], [RidePublic], []),
    'previewFare' : IDL.Func(
        [LandmarkId, LandmarkId],
        [FarePreview],
        ['query'],
      ),
    'registerDriverProfile' : IDL.Func(
        [RegisterDriverRequest],
        [DriverProfilePublic],
        [],
      ),
    'registerUser' : IDL.Func([RegisterUserRequest], [UserPublic], []),
    'rejectRide' : IDL.Func([RideId], [RidePublic], []),
    'submitRating' : IDL.Func([SubmitRatingRequest], [Rating], []),
    'updateUserPhoto' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };