/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailableDriver {
  'driverId' : UserId,
  'vehicleNumber' : string,
  'name' : string,
  'photoUrl' : string,
  'isVerified' : boolean,
  'totalRides' : bigint,
  'avgRating' : number,
}
export interface CreateRideRequest {
  'totalPassengers' : bigint,
  'genderPreference' : GenderPreference,
  'pickupLandmarkId' : LandmarkId,
  'rideType' : RideType,
  'dropoffLandmarkId' : LandmarkId,
}
export interface DriverProfilePublic {
  'userId' : UserId,
  'vehicleNumber' : string,
  'licenseId' : string,
  'isVerified' : boolean,
  'totalRides' : bigint,
  'avgRating' : number,
}
export interface FarePreview {
  'totalFare' : number,
  'fareFor1' : number,
  'fareFor2' : number,
  'fareFor3' : number,
  'fareFor4' : number,
  'distanceKm' : number,
}
export type Gender = { 'Male' : null } |
  { 'Female' : null } |
  { 'Other' : null };
export type GenderPreference = { 'Male' : null } |
  { 'NoPreference' : null } |
  { 'Female' : null };
export interface Landmark {
  'id' : LandmarkId,
  'latitude' : number,
  'landmarkType' : LandmarkType,
  'city' : string,
  'name' : string,
  'longitude' : number,
}
export type LandmarkId = bigint;
export type LandmarkType = { 'Station' : null } |
  { 'Landmark' : null } |
  { 'Metro' : null } |
  { 'Chowk' : null } |
  { 'Hospital' : null };
export interface PassengerProfilePublic {
  'userId' : UserId,
  'totalRides' : bigint,
  'avgRating' : number,
}
export interface Rating {
  'id' : RatingId,
  'createdAt' : Timestamp,
  'rideId' : RideId,
  'toUserId' : UserId,
  'score' : bigint,
  'comment' : [] | [string],
  'fromUserId' : UserId,
}
export type RatingId = bigint;
export interface RegisterDriverRequest {
  'vehicleNumber' : string,
  'licenseId' : string,
}
export interface RegisterUserRequest {
  'name' : string,
  'role' : Role,
  'photoUrl' : string,
  'gender' : Gender,
  'phone' : string,
}
export type RideId = bigint;
export interface RidePublic {
  'id' : RideId,
  'status' : RideStatus,
  'completedAt' : [] | [Timestamp],
  'driverId' : [] | [UserId],
  'startedAt' : [] | [Timestamp],
  'totalPassengers' : bigint,
  'genderPreference' : GenderPreference,
  'passengerId' : UserId,
  'pickupLandmarkId' : LandmarkId,
  'farePerPassenger' : number,
  'rideType' : RideType,
  'requestedAt' : Timestamp,
  'dropoffLandmarkId' : LandmarkId,
}
export type RideStatus = { 'Accepted' : null } |
  { 'Requested' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type RideType = { 'WomenOnly' : null } |
  { 'General' : null };
export type Role = { 'Driver' : null } |
  { 'Passenger' : null };
export interface SubmitRatingRequest {
  'rideId' : RideId,
  'toUserId' : UserId,
  'score' : bigint,
  'comment' : [] | [string],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'photoUrl' : string,
  'gender' : Gender,
  'phone' : string,
}
export interface UserRatingSummary {
  'totalRatings' : bigint,
  'avgScore' : number,
  'userId' : UserId,
  'ratings' : Array<Rating>,
}
export interface _SERVICE {
  'acceptRide' : ActorMethod<[RideId], RidePublic>,
  'cancelRide' : ActorMethod<[RideId], RidePublic>,
  'createRide' : ActorMethod<[CreateRideRequest], RidePublic>,
  'getAllLandmarks' : ActorMethod<[], Array<Landmark>>,
  'getDriverProfile' : ActorMethod<[UserId], [] | [DriverProfilePublic]>,
  'getDriverRideHistory' : ActorMethod<[], Array<RidePublic>>,
  'getIncomingRideRequests' : ActorMethod<[], Array<RidePublic>>,
  'getLandmarkById' : ActorMethod<[LandmarkId], [] | [Landmark]>,
  'getLandmarkDistance' : ActorMethod<[LandmarkId, LandmarkId], [] | [number]>,
  'getLandmarksByCity' : ActorMethod<[string], Array<Landmark>>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getMyRideHistory' : ActorMethod<[], Array<RidePublic>>,
  'getPassengerProfile' : ActorMethod<[UserId], [] | [PassengerProfilePublic]>,
  'getRatingsForUser' : ActorMethod<[UserId], UserRatingSummary>,
  'getRideById' : ActorMethod<[RideId], [] | [RidePublic]>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'listAvailableDrivers' : ActorMethod<[RideId], Array<AvailableDriver>>,
  'markDropoff' : ActorMethod<[RideId], RidePublic>,
  'markPickup' : ActorMethod<[RideId], RidePublic>,
  'previewFare' : ActorMethod<[LandmarkId, LandmarkId], FarePreview>,
  'registerDriverProfile' : ActorMethod<
    [RegisterDriverRequest],
    DriverProfilePublic
  >,
  'registerUser' : ActorMethod<[RegisterUserRequest], UserPublic>,
  'rejectRide' : ActorMethod<[RideId], RidePublic>,
  'submitRating' : ActorMethod<[SubmitRatingRequest], Rating>,
  'updateUserPhoto' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];