/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegisterUserRequest {
    name: string;
    role: Role;
    photoUrl: string;
    gender: Gender;
    phone: string;
}
export type Timestamp = bigint;
export interface Rating {
    id: RatingId;
    createdAt: Timestamp;
    rideId: RideId;
    toUserId: UserId;
    score: bigint;
    comment?: string;
    fromUserId: UserId;
}
export interface UserPublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    photoUrl: string;
    gender: Gender;
    phone: string;
}
export interface PassengerProfilePublic {
    userId: UserId;
    totalRides: bigint;
    avgRating: number;
}
export type LandmarkId = bigint;
export interface RegisterDriverRequest {
    vehicleNumber: string;
    licenseId: string;
}
export type RideId = bigint;
export interface CreateRideRequest {
    totalPassengers: bigint;
    genderPreference: GenderPreference;
    pickupLandmarkId: LandmarkId;
    rideType: RideType;
    dropoffLandmarkId: LandmarkId;
}
export interface UserRatingSummary {
    totalRatings: bigint;
    avgScore: number;
    userId: UserId;
    ratings: Array<Rating>;
}
export type UserId = Principal;
export interface RidePublic {
    id: RideId;
    status: RideStatus;
    completedAt?: Timestamp;
    driverId?: UserId;
    startedAt?: Timestamp;
    totalPassengers: bigint;
    genderPreference: GenderPreference;
    passengerId: UserId;
    pickupLandmarkId: LandmarkId;
    farePerPassenger: number;
    rideType: RideType;
    requestedAt: Timestamp;
    dropoffLandmarkId: LandmarkId;
}
export interface Landmark {
    id: LandmarkId;
    latitude: number;
    landmarkType: LandmarkType;
    city: string;
    name: string;
    longitude: number;
}
export interface SubmitRatingRequest {
    rideId: RideId;
    toUserId: UserId;
    score: bigint;
    comment?: string;
}
export interface FarePreview {
    totalFare: number;
    fareFor1: number;
    fareFor2: number;
    fareFor3: number;
    fareFor4: number;
    distanceKm: number;
}
export interface AvailableDriver {
    driverId: UserId;
    vehicleNumber: string;
    name: string;
    photoUrl: string;
    isVerified: boolean;
    totalRides: bigint;
    avgRating: number;
}
export type RatingId = bigint;
export interface DriverProfilePublic {
    userId: UserId;
    vehicleNumber: string;
    licenseId: string;
    isVerified: boolean;
    totalRides: bigint;
    avgRating: number;
}
export enum Gender {
    Male = "Male",
    Female = "Female",
    Other = "Other"
}
export enum GenderPreference {
    Male = "Male",
    NoPreference = "NoPreference",
    Female = "Female"
}
export enum LandmarkType {
    Station = "Station",
    Landmark = "Landmark",
    Metro = "Metro",
    Chowk = "Chowk",
    Hospital = "Hospital"
}
export enum RideStatus {
    Accepted = "Accepted",
    Requested = "Requested",
    Cancelled = "Cancelled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum RideType {
    WomenOnly = "WomenOnly",
    General = "General"
}
export enum Role {
    Driver = "Driver",
    Passenger = "Passenger"
}
export interface backendInterface {
    acceptRide(rideId: RideId): Promise<RidePublic>;
    cancelRide(rideId: RideId): Promise<RidePublic>;
    createRide(req: CreateRideRequest): Promise<RidePublic>;
    getAllLandmarks(): Promise<Array<Landmark>>;
    getDriverProfile(userId: UserId): Promise<DriverProfilePublic | null>;
    getDriverRideHistory(): Promise<Array<RidePublic>>;
    getIncomingRideRequests(): Promise<Array<RidePublic>>;
    getLandmarkById(id: LandmarkId): Promise<Landmark | null>;
    getLandmarkDistance(fromId: LandmarkId, toId: LandmarkId): Promise<number | null>;
    getLandmarksByCity(city: string): Promise<Array<Landmark>>;
    getMyProfile(): Promise<UserPublic | null>;
    getMyRideHistory(): Promise<Array<RidePublic>>;
    getPassengerProfile(userId: UserId): Promise<PassengerProfilePublic | null>;
    getRatingsForUser(userId: UserId): Promise<UserRatingSummary>;
    getRideById(rideId: RideId): Promise<RidePublic | null>;
    getUser(userId: UserId): Promise<UserPublic | null>;
    listAvailableDrivers(rideId: RideId): Promise<Array<AvailableDriver>>;
    markDropoff(rideId: RideId): Promise<RidePublic>;
    markPickup(rideId: RideId): Promise<RidePublic>;
    previewFare(pickupId: LandmarkId, dropoffId: LandmarkId): Promise<FarePreview>;
    registerDriverProfile(req: RegisterDriverRequest): Promise<DriverProfilePublic>;
    registerUser(req: RegisterUserRequest): Promise<UserPublic>;
    rejectRide(rideId: RideId): Promise<RidePublic>;
    submitRating(req: SubmitRatingRequest): Promise<Rating>;
    updateUserPhoto(photoUrl: string): Promise<void>;
}
import type { CreateRideRequest as _CreateRideRequest, DriverProfilePublic as _DriverProfilePublic, Gender as _Gender, GenderPreference as _GenderPreference, Landmark as _Landmark, LandmarkId as _LandmarkId, LandmarkType as _LandmarkType, PassengerProfilePublic as _PassengerProfilePublic, Rating as _Rating, RatingId as _RatingId, RegisterUserRequest as _RegisterUserRequest, RideId as _RideId, RidePublic as _RidePublic, RideStatus as _RideStatus, RideType as _RideType, Role as _Role, SubmitRatingRequest as _SubmitRatingRequest, Timestamp as _Timestamp, UserId as _UserId, UserPublic as _UserPublic, UserRatingSummary as _UserRatingSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptRide(arg0: RideId): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRide(arg0);
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRide(arg0);
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelRide(arg0: RideId): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRide(arg0);
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRide(arg0);
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRide(arg0: CreateRideRequest): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createRide(to_candid_CreateRideRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRide(to_candid_CreateRideRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLandmarks(): Promise<Array<Landmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLandmarks();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLandmarks();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverProfile(arg0: UserId): Promise<DriverProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverRideHistory(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverRideHistory();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverRideHistory();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingRideRequests(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingRideRequests();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingRideRequests();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandmarkById(arg0: LandmarkId): Promise<Landmark | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandmarkById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandmarkById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandmarkDistance(arg0: LandmarkId, arg1: LandmarkId): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandmarkDistance(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandmarkDistance(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandmarksByCity(arg0: string): Promise<Array<Landmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandmarksByCity(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandmarksByCity(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRideHistory(): Promise<Array<RidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRideHistory();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRideHistory();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassengerProfile(arg0: UserId): Promise<PassengerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassengerProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassengerProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsForUser(arg0: UserId): Promise<UserRatingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForUser(arg0);
                return from_candid_UserRatingSummary_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForUser(arg0);
            return from_candid_UserRatingSummary_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRideById(arg0: RideId): Promise<RidePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRideById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRideById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAvailableDrivers(arg0: RideId): Promise<Array<AvailableDriver>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAvailableDrivers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAvailableDrivers(arg0);
            return result;
        }
    }
    async markDropoff(arg0: RideId): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.markDropoff(arg0);
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDropoff(arg0);
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPickup(arg0: RideId): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.markPickup(arg0);
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPickup(arg0);
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async previewFare(arg0: LandmarkId, arg1: LandmarkId): Promise<FarePreview> {
        if (this.processError) {
            try {
                const result = await this.actor.previewFare(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.previewFare(arg0, arg1);
            return result;
        }
    }
    async registerDriverProfile(arg0: RegisterDriverRequest): Promise<DriverProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDriverProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDriverProfile(arg0);
            return result;
        }
    }
    async registerUser(arg0: RegisterUserRequest): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectRide(arg0: RideId): Promise<RidePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRide(arg0);
                return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRide(arg0);
            return from_candid_RidePublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRating(arg0: SubmitRatingRequest): Promise<Rating> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(to_candid_SubmitRatingRequest_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Rating_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(to_candid_SubmitRatingRequest_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Rating_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPhoto(arg0);
            return result;
        }
    }
}
function from_candid_GenderPreference_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenderPreference): GenderPreference {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_LandmarkType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandmarkType): LandmarkType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Landmark_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Landmark): Landmark {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RidePublic_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RidePublic): RidePublic {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RideType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideType): RideType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRatingSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRatingSummary): UserRatingSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverProfilePublic]): DriverProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Landmark]): Landmark | null {
    return value.length === 0 ? null : from_candid_Landmark_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PassengerProfilePublic]): PassengerProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RidePublic]): RidePublic | null {
    return value.length === 0 ? null : from_candid_RidePublic_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LandmarkId;
    latitude: number;
    landmarkType: _LandmarkType;
    city: string;
    name: string;
    longitude: number;
}): {
    id: LandmarkId;
    latitude: number;
    landmarkType: LandmarkType;
    city: string;
    name: string;
    longitude: number;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        landmarkType: from_candid_LandmarkType_n20(_uploadFile, _downloadFile, value.landmarkType),
        city: value.city,
        name: value.name,
        longitude: value.longitude
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RideId;
    status: _RideStatus;
    completedAt: [] | [_Timestamp];
    driverId: [] | [_UserId];
    startedAt: [] | [_Timestamp];
    totalPassengers: bigint;
    genderPreference: _GenderPreference;
    passengerId: _UserId;
    pickupLandmarkId: _LandmarkId;
    farePerPassenger: number;
    rideType: _RideType;
    requestedAt: _Timestamp;
    dropoffLandmarkId: _LandmarkId;
}): {
    id: RideId;
    status: RideStatus;
    completedAt?: Timestamp;
    driverId?: UserId;
    startedAt?: Timestamp;
    totalPassengers: bigint;
    genderPreference: GenderPreference;
    passengerId: UserId;
    pickupLandmarkId: LandmarkId;
    farePerPassenger: number;
    rideType: RideType;
    requestedAt: Timestamp;
    dropoffLandmarkId: LandmarkId;
} {
    return {
        id: value.id,
        status: from_candid_RideStatus_n3(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.completedAt)),
        driverId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.driverId)),
        startedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.startedAt)),
        totalPassengers: value.totalPassengers,
        genderPreference: from_candid_GenderPreference_n7(_uploadFile, _downloadFile, value.genderPreference),
        passengerId: value.passengerId,
        pickupLandmarkId: value.pickupLandmarkId,
        farePerPassenger: value.farePerPassenger,
        rideType: from_candid_RideType_n9(_uploadFile, _downloadFile, value.rideType),
        requestedAt: value.requestedAt,
        dropoffLandmarkId: value.dropoffLandmarkId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    photoUrl: string;
    gender: _Gender;
    phone: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    photoUrl: string;
    gender: Gender;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        photoUrl: value.photoUrl,
        gender: from_candid_Gender_n31(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRatings: bigint;
    avgScore: number;
    userId: _UserId;
    ratings: Array<_Rating>;
}): {
    totalRatings: bigint;
    avgScore: number;
    userId: UserId;
    ratings: Array<Rating>;
} {
    return {
        totalRatings: value.totalRatings,
        avgScore: value.avgScore,
        userId: value.userId,
        ratings: from_candid_vec_n36(_uploadFile, _downloadFile, value.ratings)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RatingId;
    createdAt: _Timestamp;
    rideId: _RideId;
    toUserId: _UserId;
    score: bigint;
    comment: [] | [string];
    fromUserId: _UserId;
}): {
    id: RatingId;
    createdAt: Timestamp;
    rideId: RideId;
    toUserId: UserId;
    score: bigint;
    comment?: string;
    fromUserId: UserId;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        rideId: value.rideId,
        toUserId: value.toUserId,
        score: value.score,
        comment: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.comment)),
        fromUserId: value.fromUserId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WomenOnly: null;
} | {
    General: null;
}): RideType {
    return "WomenOnly" in value ? RideType.WomenOnly : "General" in value ? RideType.General : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Station: null;
} | {
    Landmark: null;
} | {
    Metro: null;
} | {
    Chowk: null;
} | {
    Hospital: null;
}): LandmarkType {
    return "Station" in value ? LandmarkType.Station : "Landmark" in value ? LandmarkType.Landmark : "Metro" in value ? LandmarkType.Metro : "Chowk" in value ? LandmarkType.Chowk : "Hospital" in value ? LandmarkType.Hospital : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Driver: null;
} | {
    Passenger: null;
}): Role {
    return "Driver" in value ? Role.Driver : "Passenger" in value ? Role.Passenger : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Male: null;
} | {
    Female: null;
} | {
    Other: null;
}): Gender {
    return "Male" in value ? Gender.Male : "Female" in value ? Gender.Female : "Other" in value ? Gender.Other : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Accepted: null;
} | {
    Requested: null;
} | {
    Cancelled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): RideStatus {
    return "Accepted" in value ? RideStatus.Accepted : "Requested" in value ? RideStatus.Requested : "Cancelled" in value ? RideStatus.Cancelled : "InProgress" in value ? RideStatus.InProgress : "Completed" in value ? RideStatus.Completed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Male: null;
} | {
    NoPreference: null;
} | {
    Female: null;
}): GenderPreference {
    return "Male" in value ? GenderPreference.Male : "NoPreference" in value ? GenderPreference.NoPreference : "Female" in value ? GenderPreference.Female : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Landmark>): Array<Landmark> {
    return value.map((x)=>from_candid_Landmark_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RidePublic>): Array<RidePublic> {
    return value.map((x)=>from_candid_RidePublic_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rating>): Array<Rating> {
    return value.map((x)=>from_candid_Rating_n37(_uploadFile, _downloadFile, x));
}
function to_candid_CreateRideRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRideRequest): _CreateRideRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_GenderPreference_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenderPreference): _GenderPreference {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserRequest_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserRequest): _RegisterUserRequest {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_RideType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideType): _RideType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitRatingRequest_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitRatingRequest): _SubmitRatingRequest {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPassengers: bigint;
    genderPreference: GenderPreference;
    pickupLandmarkId: LandmarkId;
    rideType: RideType;
    dropoffLandmarkId: LandmarkId;
}): {
    totalPassengers: bigint;
    genderPreference: _GenderPreference;
    pickupLandmarkId: _LandmarkId;
    rideType: _RideType;
    dropoffLandmarkId: _LandmarkId;
} {
    return {
        totalPassengers: value.totalPassengers,
        genderPreference: to_candid_GenderPreference_n13(_uploadFile, _downloadFile, value.genderPreference),
        pickupLandmarkId: value.pickupLandmarkId,
        rideType: to_candid_RideType_n15(_uploadFile, _downloadFile, value.rideType),
        dropoffLandmarkId: value.dropoffLandmarkId
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    photoUrl: string;
    gender: Gender;
    phone: string;
}): {
    name: string;
    role: _Role;
    photoUrl: string;
    gender: _Gender;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n43(_uploadFile, _downloadFile, value.role),
        photoUrl: value.photoUrl,
        gender: to_candid_Gender_n45(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rideId: RideId;
    toUserId: UserId;
    score: bigint;
    comment?: string;
}): {
    rideId: _RideId;
    toUserId: _UserId;
    score: bigint;
    comment: [] | [string];
} {
    return {
        rideId: value.rideId,
        toUserId: value.toUserId,
        score: value.score,
        comment: value.comment ? candid_some(value.comment) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenderPreference): {
    Male: null;
} | {
    NoPreference: null;
} | {
    Female: null;
} {
    return value == GenderPreference.Male ? {
        Male: null
    } : value == GenderPreference.NoPreference ? {
        NoPreference: null
    } : value == GenderPreference.Female ? {
        Female: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideType): {
    WomenOnly: null;
} | {
    General: null;
} {
    return value == RideType.WomenOnly ? {
        WomenOnly: null
    } : value == RideType.General ? {
        General: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Driver: null;
} | {
    Passenger: null;
} {
    return value == Role.Driver ? {
        Driver: null
    } : value == Role.Passenger ? {
        Passenger: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    Male: null;
} | {
    Female: null;
} | {
    Other: null;
} {
    return value == Gender.Male ? {
        Male: null
    } : value == Gender.Female ? {
        Female: null
    } : value == Gender.Other ? {
        Other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
