/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should exclude this file from your linter and/or formatter to prevent it from being reformatted.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DriverActiveRideImport } from "./routes/driver/active-ride";
import { Route as DriverDashboardImport } from "./routes/driver/dashboard";
import { Route as DriverHistoryImport } from "./routes/driver/history";
import { Route as DriverProfileImport } from "./routes/driver/profile";
import { Route as DriverRequestsImport } from "./routes/driver/requests";
import { Route as IndexImport } from "./routes/index";
import { Route as LoginImport } from "./routes/login";
import { Route as OnboardingImport } from "./routes/onboarding";
import { Route as PassengerActiveRideImport } from "./routes/passenger/active-ride";
import { Route as PassengerBookImport } from "./routes/passenger/book";
import { Route as PassengerDashboardImport } from "./routes/passenger/dashboard";
import { Route as PassengerHistoryImport } from "./routes/passenger/history";
import { Route as PassengerProfileImport } from "./routes/passenger/profile";
import { Route as SignupImport } from "./routes/signup";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as never);

const SignupRoute = SignupImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRoute,
} as never);

const OnboardingRoute = OnboardingImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRoute,
} as never);

const PassengerDashboardRoute = PassengerDashboardImport.update({
  id: "/passenger/dashboard",
  path: "/passenger/dashboard",
  getParentRoute: () => rootRoute,
} as never);

const PassengerBookRoute = PassengerBookImport.update({
  id: "/passenger/book",
  path: "/passenger/book",
  getParentRoute: () => rootRoute,
} as never);

const PassengerActiveRideRoute = PassengerActiveRideImport.update({
  id: "/passenger/active-ride",
  path: "/passenger/active-ride",
  getParentRoute: () => rootRoute,
} as never);

const PassengerHistoryRoute = PassengerHistoryImport.update({
  id: "/passenger/history",
  path: "/passenger/history",
  getParentRoute: () => rootRoute,
} as never);

const PassengerProfileRoute = PassengerProfileImport.update({
  id: "/passenger/profile",
  path: "/passenger/profile",
  getParentRoute: () => rootRoute,
} as never);

const DriverDashboardRoute = DriverDashboardImport.update({
  id: "/driver/dashboard",
  path: "/driver/dashboard",
  getParentRoute: () => rootRoute,
} as never);

const DriverRequestsRoute = DriverRequestsImport.update({
  id: "/driver/requests",
  path: "/driver/requests",
  getParentRoute: () => rootRoute,
} as never);

const DriverActiveRideRoute = DriverActiveRideImport.update({
  id: "/driver/active-ride",
  path: "/driver/active-ride",
  getParentRoute: () => rootRoute,
} as never);

const DriverHistoryRoute = DriverHistoryImport.update({
  id: "/driver/history",
  path: "/driver/history",
  getParentRoute: () => rootRoute,
} as never);

const DriverProfileRoute = DriverProfileImport.update({
  id: "/driver/profile",
  path: "/driver/profile",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupImport;
      parentRoute: typeof rootRoute;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingImport;
      parentRoute: typeof rootRoute;
    };
    "/passenger/dashboard": {
      id: "/passenger/dashboard";
      path: "/passenger/dashboard";
      fullPath: "/passenger/dashboard";
      preLoaderRoute: typeof PassengerDashboardImport;
      parentRoute: typeof rootRoute;
    };
    "/passenger/book": {
      id: "/passenger/book";
      path: "/passenger/book";
      fullPath: "/passenger/book";
      preLoaderRoute: typeof PassengerBookImport;
      parentRoute: typeof rootRoute;
    };
    "/passenger/active-ride": {
      id: "/passenger/active-ride";
      path: "/passenger/active-ride";
      fullPath: "/passenger/active-ride";
      preLoaderRoute: typeof PassengerActiveRideImport;
      parentRoute: typeof rootRoute;
    };
    "/passenger/history": {
      id: "/passenger/history";
      path: "/passenger/history";
      fullPath: "/passenger/history";
      preLoaderRoute: typeof PassengerHistoryImport;
      parentRoute: typeof rootRoute;
    };
    "/passenger/profile": {
      id: "/passenger/profile";
      path: "/passenger/profile";
      fullPath: "/passenger/profile";
      preLoaderRoute: typeof PassengerProfileImport;
      parentRoute: typeof rootRoute;
    };
    "/driver/dashboard": {
      id: "/driver/dashboard";
      path: "/driver/dashboard";
      fullPath: "/driver/dashboard";
      preLoaderRoute: typeof DriverDashboardImport;
      parentRoute: typeof rootRoute;
    };
    "/driver/requests": {
      id: "/driver/requests";
      path: "/driver/requests";
      fullPath: "/driver/requests";
      preLoaderRoute: typeof DriverRequestsImport;
      parentRoute: typeof rootRoute;
    };
    "/driver/active-ride": {
      id: "/driver/active-ride";
      path: "/driver/active-ride";
      fullPath: "/driver/active-ride";
      preLoaderRoute: typeof DriverActiveRideImport;
      parentRoute: typeof rootRoute;
    };
    "/driver/history": {
      id: "/driver/history";
      path: "/driver/history";
      fullPath: "/driver/history";
      preLoaderRoute: typeof DriverHistoryImport;
      parentRoute: typeof rootRoute;
    };
    "/driver/profile": {
      id: "/driver/profile";
      path: "/driver/profile";
      fullPath: "/driver/profile";
      preLoaderRoute: typeof DriverProfileImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/onboarding": typeof OnboardingRoute;
  "/passenger/dashboard": typeof PassengerDashboardRoute;
  "/passenger/book": typeof PassengerBookRoute;
  "/passenger/active-ride": typeof PassengerActiveRideRoute;
  "/passenger/history": typeof PassengerHistoryRoute;
  "/passenger/profile": typeof PassengerProfileRoute;
  "/driver/dashboard": typeof DriverDashboardRoute;
  "/driver/requests": typeof DriverRequestsRoute;
  "/driver/active-ride": typeof DriverActiveRideRoute;
  "/driver/history": typeof DriverHistoryRoute;
  "/driver/profile": typeof DriverProfileRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/onboarding": typeof OnboardingRoute;
  "/passenger/dashboard": typeof PassengerDashboardRoute;
  "/passenger/book": typeof PassengerBookRoute;
  "/passenger/active-ride": typeof PassengerActiveRideRoute;
  "/passenger/history": typeof PassengerHistoryRoute;
  "/passenger/profile": typeof PassengerProfileRoute;
  "/driver/dashboard": typeof DriverDashboardRoute;
  "/driver/requests": typeof DriverRequestsRoute;
  "/driver/active-ride": typeof DriverActiveRideRoute;
  "/driver/history": typeof DriverHistoryRoute;
  "/driver/profile": typeof DriverProfileRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/onboarding": typeof OnboardingRoute;
  "/passenger/dashboard": typeof PassengerDashboardRoute;
  "/passenger/book": typeof PassengerBookRoute;
  "/passenger/active-ride": typeof PassengerActiveRideRoute;
  "/passenger/history": typeof PassengerHistoryRoute;
  "/passenger/profile": typeof PassengerProfileRoute;
  "/driver/dashboard": typeof DriverDashboardRoute;
  "/driver/requests": typeof DriverRequestsRoute;
  "/driver/active-ride": typeof DriverActiveRideRoute;
  "/driver/history": typeof DriverHistoryRoute;
  "/driver/profile": typeof DriverProfileRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/signup"
    | "/onboarding"
    | "/passenger/dashboard"
    | "/passenger/book"
    | "/passenger/active-ride"
    | "/passenger/history"
    | "/passenger/profile"
    | "/driver/dashboard"
    | "/driver/requests"
    | "/driver/active-ride"
    | "/driver/history"
    | "/driver/profile";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/onboarding"
    | "/passenger/dashboard"
    | "/passenger/book"
    | "/passenger/active-ride"
    | "/passenger/history"
    | "/passenger/profile"
    | "/driver/dashboard"
    | "/driver/requests"
    | "/driver/active-ride"
    | "/driver/history"
    | "/driver/profile";
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/signup"
    | "/onboarding"
    | "/passenger/dashboard"
    | "/passenger/book"
    | "/passenger/active-ride"
    | "/passenger/history"
    | "/passenger/profile"
    | "/driver/dashboard"
    | "/driver/requests"
    | "/driver/active-ride"
    | "/driver/history"
    | "/driver/profile";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
  OnboardingRoute: typeof OnboardingRoute;
  PassengerDashboardRoute: typeof PassengerDashboardRoute;
  PassengerBookRoute: typeof PassengerBookRoute;
  PassengerActiveRideRoute: typeof PassengerActiveRideRoute;
  PassengerHistoryRoute: typeof PassengerHistoryRoute;
  PassengerProfileRoute: typeof PassengerProfileRoute;
  DriverDashboardRoute: typeof DriverDashboardRoute;
  DriverRequestsRoute: typeof DriverRequestsRoute;
  DriverActiveRideRoute: typeof DriverActiveRideRoute;
  DriverHistoryRoute: typeof DriverHistoryRoute;
  DriverProfileRoute: typeof DriverProfileRoute;
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  SignupRoute,
  OnboardingRoute,
  PassengerDashboardRoute,
  PassengerBookRoute,
  PassengerActiveRideRoute,
  PassengerHistoryRoute,
  PassengerProfileRoute,
  DriverDashboardRoute,
  DriverRequestsRoute,
  DriverActiveRideRoute,
  DriverHistoryRoute,
  DriverProfileRoute,
]);
